title    BobOS (%ARCH%, UEFI) — XanMod (CPU récent)
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-xanmod
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-xanmod.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=4G console=ttyS0,115200
